In [2]:
import pandas as pd
import sqlite3

#load data
df = pd.read_csv('../data/diabetic_data.csv')

#connect to database
conn = sqlite3.connect('../hospital.db')

#creatate a table
df.to_sql('patients', conn, if_exists='replace', index=False)

#confirm 
pd.read_sql("SELECT * FROM patients LIMIT 5;", conn)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [3]:
#total patients 

pd.read_sql("""
SELECT COUNT(*) as total_patients
FROM patients;
""", conn)

   total_patients
0          101766

In [6]:
#Readmission Breakdown

pd.read_sql("""
SELECT readmitted, COUNT(*) as count
FROM patients
GROUP BY readmitted;
""", conn)

  readmitted  count
0        <30  11357
1        >30  35545
2         NO  54864

In [7]:
#Average Length of Stay

pd.read_sql("""
SELECT AVG(time_in_hospital) as avg_los
FROM patients;
""", conn)

    avg_los
0  4.395987

In [11]:
#ReadmissionRate by Age

pd.read_sql("""
SELECT age, 
        AVG(CASE WHEN readmitted = '<30' THEN 1 ELSE 0 END) as readmission_rate
FROM patients
GROUP BY age
ORDER BY readmission_rate DESC;
""", conn)

        age  readmission_rate
0   [20-30)          0.142426
1   [80-90)          0.120835
2   [70-80)          0.117731
3   [30-40)          0.112318
4   [60-70)          0.111284
5  [90-100)          0.110992
6   [40-50)          0.106040
7   [50-60)          0.096662
8   [10-20)          0.057887
9    [0-10)          0.018634

In [12]:
#Do longer hospital stays increase readmission risk?

pd.read_sql("""
SELECT time_in_hospital,
        AVG(CASE WHEN readmitted = '<30' THEN 1 ELSE 0 END) as readmission_rate,
        COUNT(*) as patient_count
FROM patients
GROUP BY time_in_hospital
ORDER BY time_in_hospital;
""", conn)

    time_in_hospital  readmission_rate  patient_count
0                  1          0.081785          14208
1                  2          0.099396          17224
2                  3          0.106668          17756
3                  4          0.118070          13924
4                  5          0.120309           9966
5                  6          0.125879           7539
6                  7          0.128350           5859
7                  8          0.142337           4391
8                  9          0.137242           3002
9                 10          0.143467           2342
10                11          0.105121           1855
11                12          0.133287           1448
12                13          0.123140           1210
13                14          0.129559           1042

## SQL Analysis 

### Patient Volume
### Readmission Metrics
### Length of Stay Analysis